server:
   port: 9000
#==== spring related ======#
spring:
   profiles:
      active: dev
   application:
    name: example-api
   aop:
      proxy-target-class: true

#==== connect to postgres ======#
   jpa: 
      hibernate:
         ddl-auto: update
      properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
   datasource:
      url: jdbc:postgresql://localhost:5432/docomo_example_api
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

# ====== hibernate ====
#logging:
#   level:
#      org.springframework.web: TRACE
#      org.hibernate.SQL: debug
#      org.hibernate.type: trace
#      org.springframework.security: DEBUG

app:
   telecom-api:
      url: http://localhost:9000/mock