swagger: '2.0'
info:
  version: 0.0.1
  title:  Purchase and Refund Api
  description: ''
host: 'localhost:9000'
basePath: /
tags:
  - name: Purchases
    description: 'Purchase a product'
paths:
  '/v1/purchase':
    post:
      operationId: purchaseProduct
      summary: 'Purchase a product'
      tags:
        - Purchases
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/purchase-save-request'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/response-base'
        '401':
          $ref: '#/responses/response-unauthorized'
        '500':
          $ref: '#/responses/response-internal-server-error-500'
  '/v1/purchases/{phone-number}':
      get:
        operationId: getAllTransactions
        summary: Get All transactions for a customer
        tags:
          - Purchases
        produces:
        - application/json
        parameters:
          - $ref: '#/parameters/customer-id-in-path'
        responses:
          '200':
            description: ''
            schema:
              $ref: '#/definitions/response-model-payment-transaction-list'
          '401':
            $ref: '#/responses/response-unauthorized'
          '500':
            $ref: '#/responses/response-internal-server-error-500'
  '/v1/purchases/refund':
      post:
        operationId: refundPayment
        summary: 'Refund payment'
        tags:
          - Purchases
        consumes:
        - application/json
        parameters:
          - name: body
            in: body
            schema:
              $ref: '#/definitions/refund-request' 
        responses:
          '200':
            description: ''
            schema:
              $ref: '#/definitions/response-base'
          '401':
            $ref: '#/responses/response-unauthorized'
          '500':
            $ref: '#/responses/response-internal-server-error-500'
parameters:
  customer-id-in-path:
    in: path
    name: phone-number
    type: string
    required: true
definitions:
    response-base:
      type: object
      properties:
        success:
          type: boolean
          example: 'TRUE | FALSE'
        resultCode:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Application error message.'
        errors:
          type: array
          items:
            type: string
            example: 'Exception message.'
        transactionId:
          type: string
          example: '79d9d9d3c8464e8d85f1184ab8fa4dea'
        type:
          type: string
      discriminator: type
      required:
        - success
        - resultCode
    model-enum-id-value:
      type: object
      properties:
        id: 
          type: integer
          format: int32
          example: 1000
        value:
          type: string
          example: EUR
      required:
         - id
    purchase-save-request:
      type: object
      properties:
        phoneNumber:
          type: string
          example: '+390000000009'
        productId:
          type: string
          example: 'XXXXXXXXXX'
        amount:
          type: number
          format: double
        currency:
          $ref: '#/definitions/model-enum-id-value'
      required: 
        - phoneNumber
        - productId
        - amount
        - currency
    refund-request:
      type: object
      properties:
        transactionId:
          type: string
          example: '79d9d9d3c8464e8d85f1184ab8fa4dea'
        refundReason:
          type: string
          example: 'Unintential purchase.'
      required: 
        - transactionId
        - refundReason
    model-payment-transaction:
      type: object
      properties:
        phoneNumber:
          type: string
          example: '+390000000009'
        msisdn:
          type: string
          example: 'XXXXXXXXXX'
        productId:
          type: string
          example: 'XXXXXXXXXX'
        transactionId:
          description: A transaction-id generated internally
          type: string
          example: '79d9d9d3c8464e8d85f1184ab8fa4dea'
        orderId:
          description: An order-id generated on succesful call to telecom API
          type: string
          example: 'YYYYYYYYYYYY'
        amount:
          type: number
          format: double
        currency:
          $ref: '#/definitions/model-enum-id-value'
        kind:
          type: string
          example: 'REFUND | PURCHASE'
        refundReason:
          type: string
        failureMessage:
          type: string
        status:
          type: string
          example: 'SUCCESS | FAIL | UNSURE'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    model-payment-transaction-list:
      type: object
      properties:
        transactions:
          type: array
          items: 
            $ref: '#/definitions/model-payment-transaction'
    response-model-payment-transaction-list:
      allOf:
        - $ref: '#/definitions/response-base'
        - type: object
          properties:
            returnValue:
              $ref: '#/definitions/model-payment-transaction-list'
responses:
    response-internal-server-error-500:
      description: Internal Server error
      schema:
        $ref: '#/definitions/response-base'
    response-unauthorized:
        description: Authentication information is missing or invalid
        schema:
          $ref: '#/definitions/response-base' 
        headers:
          WWW_Authenticate:
            type: string